spring:
  r2dbc:
    #    url: r2dbc:mysql://localhost:3306/dashboard_icrg
    #    password: dsj4niaga
    #    username: root
    url: r2dbc:mysql://localhost:3306/logbook
    password:
    username: root
  #    url: r2dbc:mysql://mariadbprod.cmrubv2dk8gl.ap-southeast-1.rds.amazonaws.com:3306/bills
  #    username: admin
  #    password: rAZkL3eRAWbd
  jackson:
    serialization:
      write-dates-as-timestamps: false
    #date-format: MM-dd-yyyy HH:mm:ss
    #time-zone : Asia/Ho_Chi_Minh

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    user:
      name: dimata
      password: tes

logging:
  level:
    org.springframework.data.r2dbc: TRACE
    com.dimata.service.general.contactlist: DEBUG

server:
  port: 6060
  error:
    include-stacktrace: never
custom:
  service:
    code: PS





